### ISSUE TITLE
项目启动之后，前端输入框为disabled

### ISSUE THREAD

**Issue by Mrshenxh** [vivo/MoonBox#17]
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/50947635/228441520-bd269e53-48e5-44b7-bbcc-7f8c159be662.png">

**Comment by Mrshenxh** [comment]
没办法输入IP数据。

**Comment by yananliuyanjiang** [comment]
> 没办法输入IP数据。

本地录制不需要任何输入，代码里面自行帮你完成了操作

**Comment by yananliuyanjiang** [comment]
> 但是如果我22默认端口被占用了的话，本地是不是执行不了了

不是。本地和端口没有关系，本地是直接通过java -jar拉起来你的agent。远程和端口有关系，主要是通过ssh去下发命令给机器
