### ISSUE TITLE
docker-compose up在苹果m系列上不能运行

### ISSUE THREAD

**Issue by shine10076** [vivo/MoonBox#19]
**Describe the bug**
docker-compose up 在苹果m系列的电脑上并不能运行,mysql镜像平台不匹配
![image](https://user-images.githubusercontent.com/38824616/229471725-8c6b210a-93c7-4119-b028-366d152512a8.png)

触发的问题链接
https://github.com/sprintcube/docker-compose-lamp/issues/167

修复方式:
docker-compose.yaml文件里面指定: platform: linux/amd64

**Comment by yananliuyanjiang** [comment]
> **Describe the bug** docker-compose up 在苹果m系列的电脑上并不能运行,mysql镜像平台不匹配 ![image](https://user-images.githubusercontent.com/38824616/229471725-8c6b210a-93c7-4119-b028-366d152512a8.png)
> 
> 触发的问题链接 [sprintcube/docker-compose-lamp#167](https://github.com/sprintcube/docker-compose-lamp/issues/167)
> 
> 修复方式: docker-compose.yaml文件里面指定: platform: linux/amd64

我看你这边提交了一个PR修复了这个问题，请问下这种修复本地是运行OK了吗？运行OK我就选择合并了

**Comment by shine10076** [comment]
![image](https://user-images.githubusercontent.com/38824616/229681779-fdb5d945-cb53-4680-b6a9-c2478a132b3f.png)
改完之后可以正常运行了

**Comment by yananliuyanjiang** [comment]
> ![image](https://user-images.githubusercontent.com/38824616/229681779-fdb5d945-cb53-4680-b6a9-c2478a132b3f.png) 改完之后可以正常运行了

好的，感谢提交PR。晚点我看下没问题我就直接合并了

**Comment by yananliuyanjiang** [comment]
> > ![image](https://user-images.githubusercontent.com/38824616/229681779-fdb5d945-cb53-4680-b6a9-c2478a132b3f.png) 改完之后可以正常运行了
> 
> 好的，感谢提交PR。晚点我看下没问题我就直接合并了

已经合并，非常感谢反馈和提交PR

**Comment by shine10076** [comment]
不客气，很高兴能为项目做出贡献😊
