### ISSUE TITLE
moonbox server 无法获取到 agent 的正确 IP

### ISSUE THREAD

**Issue by huang-gz** [vivo/MoonBox#23]
**Describe the bug**
moonbox 控制台录制流量时显示的 127.0.0.1， 无法显示agent 的真实 IP
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/10528066/230807115-9debf7cf-2200-441a-bc1c-72f82d30c8af.png">

**Comment by yananliuyanjiang** [comment]
> **Describe the bug** moonbox 控制台录制流量时显示的 127.0.0.1， 无法显示agent 的真实 IP <img alt="image" width="1206" src="https://user-images.githubusercontent.com/10528066/230807115-9debf7cf-2200-441a-bc1c-72f82d30c8af.png">

感谢提交修复代码
