### ISSUE TITLE
对native方法能录制么? 

### ISSUE THREAD

**Issue by 2012110325** [vivo/MoonBox#25]
咨询下:  是否支持对native方法的录制mock.  比如. java.lang.System#currentTimeMillis().

**Comment by yananliuyanjiang** [comment]
> 咨询下: 是否支持对native方法的录制mock. 比如. java.lang.System#currentTimeMillis().

native方法应该是不支持的，这个需要插桩,native方法没有能力插桩

**Comment by 2012110325** [comment]
请教下: 某个子调用, 比如sql调用: insert(Objectx o)    
class Objectx {
     long times = System.currentTimeMillis();
}
像这种回放时, 会因为子调用的参数不同, 而导致失败吧?  这种失败情况应该怎么避免.

**Comment by yananliuyanjiang** [comment]
> 请教下: 某个子调用, 比如sql调用: insert(Objectx o) class Objectx { long times = System.currentTimeMillis(); } 像这种回放时, 会因为子调用的参数不同, 而导致失败吧? 这种失败情况应该怎么避免.

像时间这类参数可以直接忽略掉。平台支持对这类字段忽略对比
