### ISSUE TITLE
http调用返回结果为org.springframework.http.ResponseEntity类型时，查看接口详情时报错

### ISSUE THREAD

**Issue by swz19941214** [vivo/MoonBox#39]
当http调用（调用类型为REST_CLIENT）的返回结果为org.springframework.http.ResponseEntity类型时，查看接口详情时会报类型错误：
"Could not write JSON: Class `java.util.HashMap` not subtype of `org.springframework.http.HttpHeaders`; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Class `java.util.HashMap` not subtype of `org.springframework.http.HttpHeaders` (through reference chain: com.vivo.internet.moonbox.common.api.dto.MoonBoxResult[\"data\"]->com.vivo.internet.moonbox.service.console.vo.RecordDetailVo[\"subInvocations\"]->java.util.ArrayList[0]->com.vivo.internet.moonbox.service.console.vo.InvocationVo[\"response\"]->org.springframework.http.ResponseEntity[\"headers\"])"

**Comment by yananliuyanjiang** [comment]
感谢PR
