### ISSUE TITLE
MoonBox 月光宝盒 Monthly Newsletter 2023-8

### ISSUE THREAD

**Issue by node** [vivo/MoonBox#50]
### ✨月光宝盒 Monthly newsletter （2023.08）
—————————————————————————
### 一、【项目开发动态】
1. 最新提交的重大PR：流量录制回放支持Motan RPC框架。该PR合并后月光宝盒将支持Dubbo和Motan两种RPC框架。PR review进行中，欢迎查看和参与，链接：https://github.com/vivo/MoonBox/pull/46 
2. 修复一个CVE，升级Spring Boot 版本 2.5.12至2.5.14
3. 为了更好地保护知识产权，本项目已开启DCO强制签署，在提交PR时需要使用-s或--signoff选项自动签署DCO。

### 二、【项目社区参与情况】
**1. 用户数**
- 微信群总人数：281

**2.GitHub**
- star总数：765
- Fork 总数：125
- Issues 提交总数：32（待处理10）
- 公开使用企业数：2
👉传送门：https://github.com/vivo

**3.Gitee**
- star总数：145
- Fork 总数：145
- Issues 提交总数：1（待处理1）
👉传送门：https://gitee.com/vivo/MoonBox

——————————————————————
欢迎各位积极参与贡献、分享案例！

**Comment by labs2020** [comment]
### ✨月光宝盒 Monthly newsletter （2023.08）
—————————————————————————
### 一、【项目开发动态】
1. 最新提交的重大PR：流量录制回放支持Motan RPC框架。该PR合并后月光宝盒将支持Dubbo和Motan两种RPC框架。PR review进行中，欢迎查看和参与，链接：https://github.com/vivo/MoonBox/pull/46 
2. 修复一个CVE，升级Spring Boot 版本 2.5.12至2.5.14 

### 二、【项目社区参与情况】
**1. 用户数**
- 微信群总人数：281

**2.Github**
- star总数：765
- Fork 总数：125
- Issues 提交总数：32（待处理10）
- 公开使用企业数：2
👉传送门：https://github.com/vivo

**3.Gitee**
- star总数：145
- Fork 总数：145
- Issues 提交总数：1（待处理1）
👉传送门：https://gitee.com/vivo/MoonBox

——————————————————————
欢迎各位积极参与贡献、分享案例！

**Comment by node** [comment]
更多动态请前往讨论区 https://github.com/vivo/MoonBox/discussions
