### ISSUE TITLE
应用标识是下拉选中的吧，可以在哪里修改吗？

### ISSUE THREAD

**Issue by alexweilai** [vivo/MoonBox#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
<img width="658" alt="image" src="https://github.com/vivo/MoonBox/assets/26303817/902556d5-eb3e-47a4-ae47-ff83af7e87fb">

**Comment by yananliuyanjiang** [comment]
可以在后端动态修改这里的逻辑

**Comment by wangtian010** [comment]
这2个选项是如何配置的？
